version: 2.1

orbs:
  node: circleci/node@1.1.6

workflows:
  version: 2
  branches:
    ignore:
      - master
      - production
      - dev-deploy
  jobs:
    - build

jobs:
  build:
    docker:
      - image: circleci/node:10.19.0
      - image: mongo:4.2.0
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install deps
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn generate:deploy